CREATE TABLE FORNECEDOR (
    COD_FORNECEDOR INT,
    NOME_FORNECEDOR VARCHAR(50),
    ENDERECO_FORNECEDOR VARCHAR(100)
);

CREATE TABLE LIVRO (
    COD_LIVRO INT,
    COD_TITULO VARCHAR(50),
    QUANT_ESTOQUE INT,
    VALOR_UNITARIO DECIMAL(10, 2)
);

CREATE TABLE PEDIDO (
    COD_PEDIDO INT,
    COD_FORNECEDOR INT,
    DATA_PEDIDO DATE,
    HORA_PEDIDO TIME,
    VALOR_TOTAL_PEDIDO DECIMAL(10, 2),
    QUANT_ITENS_PEDIDOS INT
);

CREATE TABLE ITEM_PEDIDO (
    COD_LIVRO INT,
    COD_PEDIDO INT,
    QUANTIDADE_ITEM INT,  
    VALOR_TOTAL_ITEM DECIMAL(10, 2)
);